export enum Tokens{
    //Literals
    WORD,
    STRING,
    NUMBER,
    ASSIGNMENT,

    //Vars and Expansions
    VARIABLE,
    VARIABLE_BRACED,
    COMMAND_SUB,
    COMMAND_SUB_BACKTICK,
    END_DOLLAR_COMMAND_SUB,
    ARITHMETIC,
    END_ARITHMETIC,

    //Operators
    PLUS_PLUS,
    PLUS_EQUALS,
    MINUS_MINUS,
    MINUS_EQUALS,
    ASTRIX_EQUALS,
    SLASH_EQUALS,
    PIPE,
    PIPE_AND,
    AND,
    AND_EQUALS,
    OR,
    OR_EQUALS,
    NOT,
    NOT_EQUALS,
    SEMICOLON,
    DOUBLE_SEMICOLON,
    BACKGROUND,
    EOF,
    DOUBLE_OPEN_SQUARED, //[[
    DOUBLE_CLOSE_SQUARED, //]]
    COMMENT, //#
    OPEN_BRACE,
    OPEN_PARENTHESIS,
    CLOSE_BRACE,
    CLOSE_PARENTHESIS,
    EQUALS,
    ERROR_FALLBACK,
    ASSIGN_FALLBACK,
    DEFAULT_FALLBACK,
    ALTERNATE_FALLBACK,

    //Redirectors
    REDIRECT_OUT,
    REDIRECT_APPEND,
    REDIRECT_IN,
    HEREDOC,
    HERESTRING,
    REDIRECT_ERR,
    REDIRECT_ERR_APPEND,
    REDIRECT_ALL,
    REDIRECT_ALL_APPEND,
    DUP_OUTPUT,
    DUP_INPUT,

    //Grouping
    OPEN_SUBSHELL,
    CLOSE_SUBSHELL,
    END_COMMAND_SUB,
    OPEN_COMMAND_GROUP,
    CLOSE_COMMAND_GROUP,

    //control flow
    IF,
    THEN,
    ELIF,
    ELSE,
    ENDIF,
    CASE,
    ENDCASE,
    IN,
    FOR,
    WHILE,
    UNTIL,
    DO,
    DONE,
    SELECT,

    //Funcs
    FUNCTION,
    RETURN,
    BREAK,
    CONTINUE,
    EXIT,

    //Modifiers
    EXPORT,
    LOCAL,
    READONLY,
    UNSET,
    DECLARE,
    SOURCE,
    ALIAS,
    UNALIAS,
    TIME,
    COPROC,
    PROGRAM_TOKEN,
    ARGUMENT_RECOGNISER,
    UNKNOWN_TOKEN //i will use this for errors 
}